import 'package:flutter/material.dart';
import 'tapioca.dart';
import 'main.dart';

void main() {
  runApp(const FigmaToCodeApp3());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp3 extends StatelessWidget {
  const FigmaToCodeApp3({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Iphone14ProMax7(),
        ]),
      ),
    );
  }
}

class Iphone14ProMax7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFFE4A07A)),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 430,
                  height: 180,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFC97E39),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(16),
                        bottomRight: Radius.circular(15),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 95,
                child: Container(
                  width: 382,
                  height: 45,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF6D4325),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x66000000),
                        blurRadius: 30,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 66,
                top: 109,
                child: SizedBox(
                  width: 113,
                  height: 20,
                  child: Text(
                    'Faça sua busca...',
                    style: TextStyle(
                      color: Colors.white.withAlpha(107),
                      fontSize: 13,
                      fontFamily: 'Mulish',
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
              ),
             Positioned(
                left: 33,
                top: 229,
                child: GestureDetector(
                  onTap: () {
                    Navigator.push(context,
                      MaterialPageRoute(
                        builder: (context) => FigmaToCodeApp(),
                      ),
                    );
                },
                child: Text(
                  'Frutos do Mar',
                  style: TextStyle(
                    color: const Color(0xFF6F523E),
                    fontSize: 16,
                    fontFamily: 'Mulish',
                    fontWeight: FontWeight.w800,
                  ),
                ),
                ),
              ),
              Positioned(
                left: 241,
                top: 229,
                child: Container(
                  width: 152,
                  height: 20,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Text(
                          'Acompanhamentos',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 16,
                            fontFamily: 'Mulish',
                            fontWeight: FontWeight.w800,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            Positioned(
  left: 166,
  top: 229.11,
  child: GestureDetector(
    onTap: () {
      Navigator.push(
        context,
        MaterialPageRoute(builder: (context) => FigmaToCodeApp2()),
      );
    },
    child: Container(
      width: 62.96,
      height: 24,
      child: Text(
        'Tapioca',
        style: TextStyle(
          color: const Color(0xFF6E523E),
          fontSize: 16,
          fontFamily: 'Mulish',
          fontWeight: FontWeight.w800,
          shadows: [
            Shadow(
              offset: Offset(0, 4),
              blurRadius: 4,
              color: Color(0xFF000000).withOpacity(0.25),
            ),
          ],
        ),
      ),
    ),
  ),
),
              Positioned(
                left: 264,
                top: 253,
                child: Container(
                  width: 109,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 3,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFF6CC3C8),
                      ),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 302,
                child: Container(
                  width: 179,
                  height: 231,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF976D46),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 304,
                child: Container(
                  width: 170,
                  height: 113,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/170x113"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 427,
                child: Text(
                  'Batata Frita',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Mulish',
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ),
              Positioned(
                left: 81,
                top: 504,
                child: SizedBox(
                  width: 115,
                  height: 29,
                  child: Text(
                    'R\$ 25,00',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Mulish',
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 229,
                top: 302,
                child: Container(
                  width: 179,
                  height: 231,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF976D46),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 233,
                top: 304,
                child: Container(
                  width: 170,
                  height: 113,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/170x113"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 238,
                top: 427,
                child: Text(
                  'Guaraná',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Mulish',
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ),
              Positioned(
                left: 288,
                top: 503,
                child: SizedBox(
                  width: 115,
                  height: 29,
                  child: Text(
                    'R\$ 25,00',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Mulish',
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 77,
                top: 832,
                child: Container(
                  width: 291.24,
                  height: 60,
                  decoration: BoxDecoration(color: const Color(0xFF02EDFC)),
                ),
              ),
              Positioned(
                left: 151,
                top: 847,
                child: SizedBox(
                  width: 221.50,
                  height: 29,
                  child: Text(
                    'VER PEDIDOS\n',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Mulish',
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 36,
                child: Text(
                  'Maré Alta Grill',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 32,
                    fontFamily: 'Mulish',
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 549,
                child: Container(
                  width: 179,
                  height: 231,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF976D46),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 551,
                child: Container(
                  width: 170,
                  height: 113,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/170x113"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 674,
                child: Text(
                  'Filé de Peixe',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Mulish',
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ),
              Positioned(
                left: 81,
                top: 751,
                child: SizedBox(
                  width: 115,
                  height: 29,
                  child: Text(
                    'R\$ 25,00',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Mulish',
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 229,
                top: 549,
                child: Container(
                  width: 179,
                  height: 231,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF976D46),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 233,
                top: 551,
                child: Container(
                  width: 170,
                  height: 113,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/170x113"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 238,
                top: 674,
                child: Text(
                  'Suco de Laranja',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Mulish',
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ),
              Positioned(
                left: 288,
                top: 750,
                child: SizedBox(
                  width: 115,
                  height: 29,
                  child: Text(
                    'R\$ 25,00',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Mulish',
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}