import 'package:flutter/material.dart';
import 'acompanhamentos.dart';
import 'main.dart';

void main() {
  runApp(const FigmaToCodeApp2());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp2 extends StatelessWidget {
  const FigmaToCodeApp2({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Iphone14ProMax6(),
        ]),
      ),
    );
  }
}

class Iphone14ProMax6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFFE4A07A)),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 430,
                  height: 180,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFC97E39),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(16),
                        bottomRight: Radius.circular(15),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 95,
                child: Container(
                  width: 382,
                  height: 45,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF6D4325),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x66000000),
                        blurRadius: 30,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
               Positioned(
                left: 66,
                top: 109,
                child: SizedBox(
                  width: 113,
                  height: 20,
                  child: Text(
                    'Faça sua busca...',
                    style: TextStyle(
                      color: Colors.white.withAlpha(107),
                      fontSize: 13,
                      fontFamily: 'Mulish',
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 229,
                child: GestureDetector(
                  onTap: () {
                    Navigator.push(context,
                      MaterialPageRoute(
                        builder: (context) => FigmaToCodeApp(),
                      ),
                    );
                },
                child: Text(
                  'Frutos do Mar',
                  style: TextStyle(
                    color: const Color(0xFF6F523E),
                    fontSize: 16,
                    fontFamily: 'Mulish',
                    fontWeight: FontWeight.w800,
                  ),
                ),
                ),
              ),
               Positioned(
                left: 241,
                top: 229,
                child: GestureDetector(
                  onTap: () {
                    Navigator.push(context,
                      MaterialPageRoute(
                        builder: (context) => FigmaToCodeApp3(),
                      ),
                    );
                },
                child: Container(
                  width: 152,
                  height: 20,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Text(
                          'Acompanhamentos',
                          style: TextStyle(
                            color: const Color(0xFF6E523E),
                            fontSize: 16,
                            fontFamily: 'Mulish',
                            fontWeight: FontWeight.w800,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                ),
              ),
              Positioned(
                left: 166,
                top: 229.11,
                child: Container(
                  width: 62.96,
                  height: 24,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 63,
                          height: 24.11,
                          child: Text(
                            'Tapioca',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Mulish',
                              fontWeight: FontWeight.w800,
                              shadows: [Shadow(offset: Offset(0, 4), blurRadius: 4, color: Color(0xFF000000).withOpacity(0.25))],
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 166,
                top: 253,
                child: Container(
                  width: 63,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 3,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFF6CC3C8),
                      ),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 302,
                child: Container(
                  width: 179,
                  height: 231,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF976D46),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 304,
                child: Container(
                  width: 170,
                  height: 113,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://imgs.search.brave.com/cK06ufipRuoWFHl1-tRMlyE_9MPRHO17ayCOZAkssqs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9yZWNl/aXRhZGVsaWNpYS5j/b20uYnIvd29yZHBy/ZXNzL3dwLWNvbnRl/bnQvZmlsZXMvcmVj/ZWl0YWRlbGljaWEu/Y29tLmJyLzIwMjQv/MDUvdGFwaW9jYS1k/ZS1jYW1hcmFvLWNv/bWJpbmUtc2ltcGxp/Y2lkYWRlLWUtc29m/aXN0aWNhY2FvMi03/Njh4NTEyLndlYnA"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 427,
                child: Text(
                  'Tapioca de Camarão',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Mulish',
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ),
              Positioned(
                left: 81,
                top: 504,
                child: SizedBox(
                  width: 115,
                  height: 29,
                  child: Text(
                    'R\$ 25,00',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Mulish',
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 229,
                top: 302,
                child: Container(
                  width: 179,
                  height: 231,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF976D46),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 233,
                top: 304,
                child: Container(
                  width: 170,
                  height: 113,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://imgs.search.brave.com/neFluyPVR30OVHwIXeeMc-bjOhzcWjJO0qsXBwSCH1w/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZXN0YWRhby5jb20u/YnIvcmVzaXplci92/Mi8yWjNaU1NTMjdC/QUozQ0tTWVJHVVRB/R0M2WS5qcGc_cXVh/bGl0eT04MCZhdXRo/PWE1ZjU3NzU2OWFj/NDlmMTIxZmY2NDg3/NzEyNGM2ZWNjYjA4/YzE4MWY4NGUxNGJk/OTBhZDE3NDY4MmQw/NDllODImd2lkdGg9/NzIwJmhlaWdodD01/MDMmc21hcnQ9dHJ1/ZQ"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 238,
                top: 427,
                child: Text(
                  'Tapioca Doce',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Mulish',
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ),
              Positioned(
                left: 288,
                top: 503,
                child: SizedBox(
                  width: 115,
                  height: 29,
                  child: Text(
                    'R\$ 10,00',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Mulish',
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 77,
                top: 832,
                child: Container(
                  width: 291.24,
                  height: 60,
                  decoration: BoxDecoration(color: const Color(0xFF02EDFC)),
                ),
              ),
               Positioned(
                left: 77,
                top: 832,
                child: Container(
                  width: 291.24,
                  height: 60,
                  decoration: BoxDecoration(
                    color: const Color(0xFF02EDFC),
                    borderRadius: BorderRadius.circular(12), // Bordas arredondadas
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.2),
                        blurRadius: 8,
                        offset: Offset(0, 4),
                      ),
                    ],
                  ),
                  child: Center(
                    child: Text(
                      'VER PEDIDOS',
                      style: TextStyle(
                        color: Colors.white, // Melhor contraste
                        fontSize: 20,
                        fontFamily: 'Mulish',
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 36,
                child: Text(
                  'Maré Alta Grill',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 32,
                    fontFamily: 'Mulish',
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 549,
                child: Container(
                  width: 179,
                  height: 231,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF976D46),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 551,
                child: Container(
                  width: 170,
                  height: 113,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://imgs.search.brave.com/g7cWQoAs4N1lldCKQIeyMrfymUpX_nvmjPCYtgdHU7o/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMuaXRkZy5jb20u/YnIvaW1hZ2VzLzM2/MC0yNDAvNTAxN2Qz/ZThhMTI3NDE3ZDM5/NjA3ZWMwYjQzZjZi/MzYvOTk3NTMtb3Jp/Z2luYWwuanBn"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 674,
                child: Text(
                  'Tapioca Mista',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Mulish',
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ),
              Positioned(
                left: 81,
                top: 751,
                child: SizedBox(
                  width: 115,
                  height: 29,
                  child: Text(
                    'R\$ 9,00',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Mulish',
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 229,
                top: 549,
                child: Container(
                  width: 179,
                  height: 231,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF976D46),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 233,
                top: 551,
                child: Container(
                  width: 170,
                  height: 113,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://imgs.search.brave.com/GqRy0Sz4Bx8jYUpa-LHRGAwy6wtHziAkybq6SeRPBKY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzkzL2Zl/L2FmLzkzZmVhZmU5/ODZlNWFiM2ViOWZk/ZWEyNGQxNWEwMDU5/LmpwZw"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 238,
                top: 674,
                child: Text(
                  'Tapioca de Frango',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Mulish',
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ),
              Positioned(
                left: 288,
                top: 750,
                child: SizedBox(
                  width: 115,
                  height: 29,
                  child: Text(
                    'R\$ 12,00',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Mulish',
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}